TheaterBooking.Web/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using TheaterBooking.Infrastructure;
using TheaterBooking.Entities;


namespace TheaterBooking.Web.Controllers
{
    public class PageController : Controller
    {
        private readonly IRepository<DynamicPage> _dynamicPageRepository;
        public PageController(IRepository<DynamicPage> dynamicPageRepos)
        {
            _dynamicPageRepository = dynamicPageRepos;
        }


        private bool NameDoesExists(string pageName)
        {
            return _dynamicPageRepository.Count(o => o.Name == pageName.ToLower()) > 0;
        }
        private DynamicPage GetByName(string name)
        {
            DynamicPage item = _dynamicPageRepository.FindOne(o => o.Name == name.ToLower());
            return item;
        }



        [HttpGet]
        public ActionResult Show(string id)
        {
            var item = GetByName(id);

            if (item != null)
                return View(item);
            else
                return HttpNotFound();
        }


        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Manage()
        {
            var pages = _dynamicPageRepository.List();
            return View(pages);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateInput(false)]
        public ActionResult Create(DynamicPage item)
        {
            if (ModelState.IsValid)
            {
                item.Name = item.Name.Replace(" ", "_");

                if (!NameDoesExists(item.Name))
                {
                    DynamicPage newPage = new DynamicPage();
                    newPage.Name = item.Name.ToLower();
                    newPage.LastUpdate = newPage.CreationDate = DateTime.UtcNow;
                    newPage.Title = item.Title;
                    newPage.Summary = item.Summary;
                    newPage.Text = item.Text;
                    newPage.Tags = item.Tags;

                    _dynamicPageRepository.Save(newPage);

                    return RedirectToAction("Manage");
                }
                else
                {
                    ModelState.AddModelError("", "صفحه دیگری با نام انتخاب شده وجود دارد، از نام دیگری استفاده نمایید");
                    return View();
                }
            }
            else
            {
                ModelState.AddModelError("", "ابتدا اطلاعات خواسته شده را وارد نمایید");
                return View();
            }


        }


        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(string id)
        {
            var item = GetByName(id);

            if (item != null)
                return View(item);
            else
                return HttpNotFound();
        }


        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateInput(false)]
        public ActionResult Edit(string id, DynamicPage item)
        {
            var oldItem = GetByName(id);

            if (oldItem != null)
            {
                oldItem.Title = item.Title;
                oldItem.Summary = item.Summary;
                oldItem.Text = item.Text;
                oldItem.Tags = item.Tags;
                oldItem.LastUpdate = DateTime.UtcNow;

                _dynamicPageRepository.Save(oldItem);

                return RedirectToAction("Manage");
            }
            else
                return HttpNotFound();
        }


        [Authorize(Roles = "admin")]
        public ActionResult Delete(string id)
        {
            var item = GetByName(id);

            if (item != null)
            {
                _dynamicPageRepository.Delete(item.DynamicPageId);
                return RedirectToAction("Manage");
            }
            else
                return HttpNotFound();
        }



    }

}

TheaterBooking.Web/Controllers/SalonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheaterBooking.Entities;
using TheaterBooking.Infrastructure;
using TheaterBooking.Web.ViewModels;

namespace TheaterBooking.Web.Controllers
{
    public class SalonController : Controller
    {
        private readonly IRepository<Salon> salonRepository;

        public SalonController(IRepository<Salon> salonRepos)
        {
            this.salonRepository = salonRepos;
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Manage()
        {
            var salons = salonRepository.List();
            return View(salons);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult Create(Salon model)
        {
            //dynamic seatsLayout = Utils.DynamicJSON.Parse(seatsLayoutJSON);

            var newSalon = new Salon();
            newSalon.Title = model.Title;
            newSalon.Address = model.Address;
            newSalon.Phone = model.Phone;

            salonRepository.Save(model);

            return RedirectToAction("Manage");
        }


        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int Id)
        {
            var salon = salonRepository.Get(Id);
            if (salon != null)
            {
                salonRepository.Delete(Id);
            }
            else
                return HttpNotFound();

            return RedirectToAction("Manage");
        }


        [HttpGet]
        public JsonResult GetSeatLayout(int Id)
        {
            var salon = salonRepository.Get(Id);
            if (salon != null)
            {
                var rows = salon.SeatRows.OrderBy(o => o.RowIndex).ToList();
                int[] result = new int[rows.Count];
                for (int i = 0; i < result.Length; i++)
                {
                    result[i] = rows[i].SeatsCount;
                }

                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
                return null;
        }
    }
}

TheaterBooking.Web/Controllers/ShowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheaterBooking.Entities;
using TheaterBooking.Infrastructure;

namespace TheaterBooking.Web.Controllers
{
    public class ShowController : Controller
    {
        private readonly IRepository<Show> showRepository;

        public ShowController(IRepository<Show> showRepos)
        {
            this.showRepository = showRepos;
        }


        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Manage()
        {
            var shows = showRepository.List().OrderByDescending(o => o.CreationDate);

            return View(shows);
        }


        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        [Authorize(Roles = "admin")]
        public ActionResult Create(Show model)
        {
            if (ModelState.IsValid)
            {
                Show newShow = new Show();
                newShow.IsActive = true;
                newShow.Title = model.Title;
                newShow.ImageUrl = model.ImageUrl;
                newShow.Description = model.Description;
                newShow.CreationDate = DateTime.UtcNow;

                this.showRepository.Save(newShow);

                return RedirectToAction("Manage");
            }
            else
            {
                ModelState.AddModelError("", "ابتدا مقادیر خواسته شده را وارد نمایید");
                return View();
            }
        }



        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int Id)
        {
            var show = showRepository.Get(Id);
            if (show != null)
            {
                return View(show);
            }
            else
                return HttpNotFound();

        }

        [HttpPost]
        [ValidateInput(false)]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(Show model)
        {
            var show = showRepository.Get(model.ShowId);
            if (show != null)
            {
                if (ModelState.IsValid)
                {
                    show.Title = model.Title;
                    show.ImageUrl = model.ImageUrl;
                    show.Description = model.Description;
                    showRepository.Save(show);

                    return RedirectToAction("Manage");
                }
                else
                {
                    ModelState.AddModelError("", "ابتدا مقادیر خواسته شده را وارد نمایید");
                    return View();
                }
            }
            else
                return HttpNotFound();

        }



        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int Id)
        {
            var show = showRepository.Get(Id);
            if (show != null)
            {
                showRepository.Delete(Id);
                return RedirectToAction("Manage");
            }
            else
                return HttpNotFound();

        }

    }
}

TheaterBooking.Web/Views/Shared/UnderConstruction.cshtml
@{
    ViewBag.Title = "در دست تهیه";
    
}
<h2>
در دست تهیه...
</h2>

TheaterBooking.Web/Views/Shared/_CC_DateSelector.cshtml
@{ 
    System.Web.Routing.RouteValueDictionary parameters = new System.Web.Routing.RouteValueDictionary(Model);
    string fieldName = parameters["Name"].ToString();

    int StartYear = Convert.ToInt32(parameters["StartYear"]);
    int EndYear = Convert.ToInt32(parameters["EndYear"]);
    string[] Months = (string[])parameters["Months"];

    string currentCulture = parameters["CurrentCulture"].ToString();
    string convertorUrl = parameters["ConvertorURL"].ToString();
    string daysInMonthUrl = parameters["DaysInMonthURL"].ToString();
}
@{
    if (ViewContext.TempData["DateSelectorScriptsIncluded"] == null)
    { 
    <script src="@Url.Content("~/Scripts/Controls/dateselector.js")" type="text/javascript"></script>
        ViewContext.TempData["DateSelectorScriptsIncluded"] = true;
    }
}
<div class="ds_ptr_container" data-currentculture="@currentCulture" data-convertorurl="@convertorUrl" data-daysinmonthurl="@daysInMonthUrl">
    <select class="ds_ptr_year" style="width: 60px;">
        @{
            for (int i = StartYear; i <= EndYear; i++)
            {
            <option>@i.ToString()</option>
            }
        }
    </select>
    <select class="ds_ptr_month" style="width: 80px;">
        @{
            for (int i = 0; i < Months.Length - 1; i++)
            {
            <option value="@(i + 1)">@Months[i]</option>       
            }
        }
    </select>
    <select class="ds_ptr_day" style="width: 50px;">
        @{
            for (int i = 1; i <= 31; i++)
            {
            <option>@i.ToString()</option>
            }
        }
    </select>
    <img class="ds_ptr_loading" style="display:none;" src="@Url.Content("~/Content/images/ajax-loader.gif")" />
    <input type="hidden" name="@fieldName" id="@fieldName" class="ds_ptr_value" />
</div>

TheaterBooking.Web/Views/Shared/_CC_TimeSelector.cshtml
@{ 
    System.Web.Routing.RouteValueDictionary parameters = new System.Web.Routing.RouteValueDictionary(Model);
    string fieldName = parameters["Name"].ToString();
}
@{
    
    if (TempData["TimeSelectorScriptsIncluded"] == null)
    {
        
    <script type="text/javascript">
        $(function () {

            $(".ts_ptr_hour, .ts_ptr_minute").change(function () {
                var container = $(this).parents(".ts_ptr_container");
                var selectedTime = container.find(".ts_ptr_hour").val() + ":" + container.find(".ts_ptr_minute").val() + ":" + "00";

                container.find(".ts_ptr_value").val(selectedTime);
            });
        });
    </script>
    
        TempData["TimeSelectorScriptsIncluded"] = true;
    }
}


<div class="ts_ptr_container">
    <select class="ts_ptr_hour" style="width: 50px;">
        @{
            for (int i = 0; i < 24; i++)
            {
            <option>@(string.Format("{0:00}", i))</option>
            }
        }
    </select>
    :
    <select class="ts_ptr_minute" style="width: 50px;">
        @{
            for (int i = 0; i < 60; i++)
            {
            <option>@(string.Format("{0:00}", i))</option>    
            }
        }
    </select>
    <input type="hidden" name="@fieldName" id="@fieldName" class="ts_ptr_value" />
</div>

TheaterBooking.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>SharangTeathre - @ViewBag.Title</title>
    <link href="@Url.Content("~/Content/MainTheme.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery/jquery-1.4.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery/jquery.tinyscrollbar.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/extensions.js")" type="text/javascript"></script>
    @RenderSection("Head", false)
</head>
<body>
    <div id="tm-container">
        <div id="tm-header">
            <div id="tm-header-bar">
                <a href="@Url.Action("Index", "Home")">
                    <div style="width: 100px; height: 100%; display: block; float: right;">
                    </div>
                </a>
                <div id="tm-header-bar-container">
                    <div id="tm-header-bar-content">
                        @{Html.RenderPartial("_UserPanel");}
                    </div>
                </div>
            </div>
        </div>
        <div id="tm-main">
            <div id="tm-main-content">
                <div class="marginBox">
                    @RenderBody()
                </div>
            </div>
            <div id="tm-main-menu">
                <div id="tm-main-menu-rightbg">
                </div>
                <div id="tm-main-menu-content">
                    <ul id="mainmenu">
                        <a href="@(Url.Action("Index", "Home"))">
                            <li id="mainmenu-home"></li>
                        </a><a href="@Url.Action("Manage", "Show")">
                            <li id="mainmenu-archive"></li>
                        </a><a href="@Url.Action("Show", "Page", new { Id = "About_Us" })">
                            <li id="mainmenu-about"></li>
                        </a></a><a href="@Url.Action("Show", "Page", new { Id = "Contact_Us" })">
                            <li id="mainmenu-contact"></li>
                        </a><a href="@Url.Action("Show", "Page", new { Id = "News" })">
                            <li id="mainmenu-news"></li>
                        </a>
                    </ul>
                </div>
                <div id="tm-main-menu-leftbg">
                </div>
            </div>
        </div>
        <div id="tm-footer">
            <div id="tm-footer-box">
                تمامی حقوق سایت برای شرنگ محفوظ میباشد
                <br />
                Copyright © 2011 - All rights reserved
            </div>
        </div>
    </div>
</body>
</html>

TheaterBooking.Web/Views/Shared/_UserPanel.cshtml
@{
    //bool userIsAuthenticated = true;
    bool userIsAuthenticated = User.Identity.IsAuthenticated;
}
<div style="float: right;">
    @if (userIsAuthenticated)
    {
        <div>
            <ul id="tm-usermenu">
                @if (Roles.IsUserInRole(Membership.GetUser().UserName, "admin"))
                {
                    <li>@Html.ActionLink("مدیریت نمایش ها", "Manage", "Show")</li>
                    <li>|</li>
                    <li>@Html.ActionLink("مدیریت سالن ها", "Manage", "Salon")</li>
                    <li>|</li>
                    <li>@Html.ActionLink("مدیریت کاربران", "Manage", "Account")</li>  
                    <li>|</li>
                    <li>@Html.ActionLink("مدیریت صفحات", "Manage", "Page")</li>
                  
                    <li></li>
                    <li></li>
                    <li></li>
                }
                <li>@Html.ActionLink("خروج", "SignOut", "Account") &nbsp;&nbsp;(@User.Identity.Name)</li>
                <li>|</li>
                <li>@Html.ActionLink("تغییر کلمه عبور", "ChangePassword", "Account")</li>
            </ul>
        </div>
    }
    else
    {
        using (Html.BeginForm("SignIn", "Account"))
        {
        <text> نام کاربری :</text>
        <input style="width: 100px; margin-left: 15px;" type="text" name="Username" />
        <text> کلمه عبور :</text>
        <input style="width: 100px; margin-left: 10px;" type="password" name="Password" />
        <input class="themedButton" type="submit" value="ورود" />
        }
    }
</div>